### ISSUE TITLE
Can't have other winodws over the World Maker window.

### ISSUE THREAD

**Issue by RawrTheDinosawr1** [mayank-prasoon/world-maker#2]
I cannot place other windows, for example Discord, over the World Maker window, in order to see other windows I have to close or minimize the program.

I'm on a Windows 10 computer and my system stats are:
Processor: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz   3.00 GHz
8 gigabytes of ram.
64 bit operating system.

**Comment by mayank-prasoon** [comment]
Hi,
I forgot to disable the Always on top feature. I will disable it.
